import { env } from "cloudflare:workers";
export type DemoSource = { id: string; source: string; title: string; content: string; version: string; updatedAt: string; url: string };
export type Finding = { statement: string; sourceIds: string[] };
const seeds: DemoSource[] = [
  { id: "slack-acme", source: "Slack", title: "#acme-account · Deployment thread", content: "Security review is the final blocker. The account team is waiting on the questionnaire before confirming production access.", version: "1719853200.000", updatedAt: "Jul 18, 2026", url: "https://slack.com/demo/acme" },
  { id: "github-184", source: "GitHub", title: "Issue #184 · Complete security review", content: "BLOCKED: Eight security questionnaire items remain unanswered. Owner: Priya. Production deployment cannot proceed.", version: "2026-07-19T14:10:00Z", updatedAt: "Jul 19, 2026", url: "https://github.com/demo/knowy/issues/184" },
  { id: "drive-plan", source: "Google Drive", title: "Acme Deployment Plan", content: "Production launch requires completed security approval. Target launch: July 22. Engineering work is otherwise complete.", version: "2026-07-18T09:20:00Z", updatedAt: "Jul 18, 2026", url: "https://drive.google.com/demo/acme-plan" },
];
const db = () => env.DB;
export async function ensureStore() { const d1 = db(); await d1.batch([d1.prepare("CREATE TABLE IF NOT EXISTS source_records (id TEXT PRIMARY KEY, source TEXT NOT NULL, title TEXT NOT NULL, content TEXT NOT NULL, version TEXT NOT NULL, updated_at TEXT NOT NULL, url TEXT NOT NULL)"), d1.prepare("CREATE TABLE IF NOT EXISTS intelligence_objects (id TEXT PRIMARY KEY, topic TEXT NOT NULL, answer TEXT NOT NULL, findings TEXT NOT NULL, confidence REAL NOT NULL, status TEXT NOT NULL, checked_at TEXT NOT NULL)"), d1.prepare("CREATE TABLE IF NOT EXISTS intelligence_dependencies (intelligence_id TEXT NOT NULL, source_id TEXT NOT NULL, source_version TEXT NOT NULL, PRIMARY KEY (intelligence_id, source_id))"), d1.prepare("CREATE TABLE IF NOT EXISTS query_history (id INTEGER PRIMARY KEY AUTOINCREMENT, question TEXT NOT NULL, mode TEXT NOT NULL, created_at TEXT NOT NULL)")]); for (const s of seeds) await d1.prepare("INSERT OR IGNORE INTO source_records VALUES (?, ?, ?, ?, ?, ?, ?)").bind(s.id,s.source,s.title,s.content,s.version,s.updatedAt,s.url).run(); }
export async function getSources(): Promise<DemoSource[]> { await ensureStore(); return (await db().prepare("SELECT id,source,title,content,version,updated_at AS updatedAt,url FROM source_records").all<DemoSource>()).results; }
export async function resetStore() { await ensureStore(); await db().batch([db().prepare("DELETE FROM intelligence_dependencies"),db().prepare("DELETE FROM intelligence_objects"),db().prepare("DELETE FROM query_history"),db().prepare("DELETE FROM source_records")]); for (const s of seeds) await db().prepare("INSERT INTO source_records VALUES (?, ?, ?, ?, ?, ?, ?)").bind(s.id,s.source,s.title,s.content,s.version,s.updatedAt,s.url).run(); }
export async function resolveGithubIssue() { await ensureStore(); await db().prepare("UPDATE source_records SET content=?,version=?,updated_at=? WHERE id='github-184'").bind("RESOLVED: All security questionnaire items are answered. Security approval is complete and production deployment may proceed.","2026-07-20T20:00:00Z","Just now").run(); }
export async function readIntelligence() { await ensureStore(); return db().prepare("SELECT * FROM intelligence_objects WHERE id='acme-deployment'").first<{answer:string;findings:string;confidence:number;status:string;checked_at:string}>(); }
export async function readDependencies() { return (await db().prepare("SELECT source_id AS sourceId,source_version AS sourceVersion FROM intelligence_dependencies WHERE intelligence_id='acme-deployment'").all<{sourceId:string;sourceVersion:string}>()).results; }
export async function saveIntelligence(input:{answer:string;findings:Finding[];confidence:number;status:string},sources:DemoSource[]){const now=new Date().toISOString();await db().prepare("INSERT INTO intelligence_objects VALUES ('acme-deployment','Acme deployment',?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET answer=excluded.answer,findings=excluded.findings,confidence=excluded.confidence,status=excluded.status,checked_at=excluded.checked_at").bind(input.answer,JSON.stringify(input.findings),input.confidence,input.status,now).run();await db().prepare("DELETE FROM intelligence_dependencies WHERE intelligence_id='acme-deployment'").run();for(const s of sources)await db().prepare("INSERT INTO intelligence_dependencies VALUES ('acme-deployment',?,?)").bind(s.id,s.version).run();return now;}
export async function logQuery(question:string,mode:string){await db().prepare("INSERT INTO query_history(question,mode,created_at) VALUES(?,?,?)").bind(question,mode,new Date().toISOString()).run();}
